import { Node, Edge } from '@xyflow/react';

export interface Tag {
  id: string;
  name: string;
  color: string;
}

export type BorderStyle = 'circle' | 'rounded' | 'diamond' | 'hexagon' | 'card' | 'glow' | 'square' | 'dashed';
export type UnitType = 'currency' | 'custom' | 'none';

export interface TemplateData {
  title: string;
  tags: Tag[];
  customUnits: string[];
  nodes: Node[];
  edges: Edge[];
}

export type TemplateLanguage = 'pt' | 'en';

const TEMPLATES_PT: Record<string, TemplateData> = {
  blank: {
    title: 'Meu Projeto Vulcanode',
    tags: [
      { id: 't-1', name: 'Comum', color: '#64748b' },
      { id: 't-2', name: 'Raro', color: '#f59e0b' },
      { id: 't-3', name: 'Lendário', color: '#ff6a13' },
      { id: 't-4', name: 'Móvel', color: '#ea580c' },
      { id: 't-5', name: 'Componente', color: '#10b981' },
    ],
    customUnits: ['pçs', 'kg', 'un', 'barras'],
    nodes: [],
    edges: [],
  },
  rpg: {
    title: 'Crafting Tree: Espada Mestra de Vulcano',
    tags: [
      { id: 'rpg-1', name: 'Comum', color: '#71717a' },
      { id: 'rpg-2', name: 'Incomum', color: '#10b981' },
      { id: 'rpg-3', name: 'Raro', color: '#3b82f6' },
      { id: 'rpg-4', name: 'Lendário', color: '#a855f7' },
      { id: 'rpg-5', name: 'Mítico', color: '#ff6a13' },
    ],
    customUnits: ['barras', 'gemas', 'un'],
    nodes: [
      {
        id: 'item-espada',
        type: 'itemNode',
        position: { x: 480, y: 45 },
        data: {
          name: 'Espada Mestra de Vulcano',
          subtitle: 'Arma Mítica da Forja Solar',
          description: 'Uma lâmina capaz de cortar montanhas, forjada nas chamas centenárias do monte Etna pelo próprio Deus do Fogo.',
          url: 'https://pt.wikipedia.org/wiki/Vulcano_(mitologia)',
          icon: 'Sword',
          quantity: 1,
          cost: 1500,
          unitType: 'currency',
          customUnit: '',
          tagId: 'rpg-5',
          borderStyle: 'diamond',
          collapsed: false,
        },
      },
      {
        id: 'station-forja',
        type: 'stationNode',
        position: { x: 480, y: 255 },
        data: {
          name: 'Fornalha Solar • 5 min',
          subtitle: 'Estação Obrigatória de Fundição',
          description: 'Passagem obrigatória de tempo pela temperatura do magma incandescente para unir minérios e chamas.',
          icon: 'Flame',
          borderStyle: 'hexagon',
          collapsed: false,
        },
      },
      {
        id: 'item-ferro',
        type: 'itemNode',
        position: { x: 300, y: 435 },
        data: {
          name: 'Minério de Ferro Refinado',
          subtitle: 'Componente Metálico Padrão',
          description: 'Blocos pesados de metal extraídos do coração vulcânico da rocha.',
          icon: 'Box',
          quantity: 5,
          cost: 20,
          unitType: 'custom',
          customUnit: 'barras',
          tagId: 'rpg-1',
          borderStyle: 'circle',
          collapsed: false,
        },
      },
      {
        id: 'item-carvao',
        type: 'itemNode',
        position: { x: 660, y: 435 },
        data: {
          name: 'Carvão de Magma',
          subtitle: 'Combustível de Fogo ETERNO',
          description: 'Chamas encapsuladas em minerais escuras que liberam energia explosiva constante.',
          icon: 'Zap',
          quantity: 3,
          cost: 50,
          unitType: 'custom',
          customUnit: 'gemas',
          tagId: 'rpg-2',
          borderStyle: 'circle',
          collapsed: false,
        },
      },
    ],
    edges: [
      {
        id: 'e-forja-espada',
        source: 'station-forja',
        target: 'item-espada',
        type: 'customEdge',
        animated: true,
        data: { label: 'Fundição Perfeita' },
      },
      {
        id: 'e-ferro-forja',
        source: 'item-ferro',
        target: 'station-forja',
        type: 'customEdge',
        animated: true,
        data: { label: '5 barras' },
      },
      {
        id: 'e-carvao-forja',
        source: 'item-carvao',
        target: 'station-forja',
        type: 'customEdge',
        animated: true,
        data: { label: '3 gemas' },
      },
    ],
  },
  budget: {
    title: 'Composição Modular: Casamento & Moradia',
    tags: [
      { id: 'bd-1', name: 'Móveis', color: '#ff6a13' },
      { id: 'bd-2', name: 'Eletros', color: '#ea580c' },
      { id: 'bd-3', name: 'Componente Fixo', color: '#f59e0b' },
      { id: 'bd-4', name: 'Meta Principal', color: '#ff6a13' },
    ],
    customUnits: ['pçs', 'm²', 'mês', 'un'],
    nodes: [
      // Objetivo Final: Casamento no topo (Pai)
      {
        id: 'goal-casamento',
        type: 'itemNode',
        position: { x: 510, y: 45 },
        data: {
          name: 'Casamento & Lar',
          subtitle: 'Projeto de Vida em Conjunto',
          description: 'O topo da nossa árvore de composição modular unindo os custos da moradia e da festa de celebração.',
          icon: 'Heart',
          quantity: 1,
          cost: 0,
          unitType: 'currency',
          customUnit: '',
          tagId: 'bd-4',
          borderStyle: 'diamond',
          collapsed: false,
        },
      },
      // Pais intermediários na camada de meio
      {
        id: 'comp-casa',
        type: 'itemNode',
        position: { x: 300, y: 240 },
        data: {
          name: 'Composição Casa',
          subtitle: 'Móveis & Aluguel do Novo Lar',
          description: 'Soma de todos os componentes eletrodomésticos e estruturais indispensáveis.',
          icon: 'Home',
          quantity: 1,
          cost: 0,
          unitType: 'currency',
          customUnit: '',
          tagId: 'bd-3',
          borderStyle: 'rounded',
          collapsed: false,
        },
      },
      {
        id: 'comp-festa',
        type: 'itemNode',
        position: { x: 720, y: 240 },
        data: {
          name: 'Celebração & Festa',
          subtitle: 'Evento e Gastronomia',
          description: 'Recepção especial com Buffet e celebração com amigos.',
          icon: 'Sparkles',
          quantity: 1,
          cost: 0,
          unitType: 'currency',
          customUnit: '',
          tagId: 'bd-4',
          borderStyle: 'rounded',
          collapsed: false,
        },
      },
      // Componentes de base (Ingredientes/Insumos) abaixo
      {
        id: 'item-geladeira',
        type: 'itemNode',
        position: { x: 135, y: 450 },
        data: {
          name: 'Geladeira Inox',
          subtitle: 'Eletrodoméstico Essencial',
          description: 'Refrigerador Frost Free 450 litros com tecnologia inverter e economia A+++.',
          icon: 'Box',
          quantity: 1,
          cost: 3000,
          unitType: 'currency',
          customUnit: '',
          tagId: 'bd-2',
          borderStyle: 'circle',
        },
      },
      {
        id: 'item-fogao',
        type: 'itemNode',
        position: { x: 300, y: 450 },
        data: {
          name: 'Fogão Cooktop',
          subtitle: 'Forno & Fogão 5 Bocas',
          description: 'Mesa de vidro temperado com chamas rápidas para gastronomia doméstica.',
          icon: 'Flame',
          quantity: 1,
          cost: 2000,
          unitType: 'currency',
          customUnit: '',
          tagId: 'bd-2',
          borderStyle: 'circle',
        },
      },
      {
        id: 'item-aluguel',
        type: 'itemNode',
        position: { x: 465, y: 450 },
        data: {
          name: 'Aluguel do Mês',
          subtitle: 'Despesa Corrente de Locação',
          description: 'Gasto mensal com aluguel do apartamento e taxas condominiais.',
          icon: 'Key',
          quantity: 1,
          cost: 1500,
          unitType: 'currency',
          customUnit: '',
          tagId: 'bd-3',
          borderStyle: 'circle',
        },
      },
      {
        id: 'item-buffet',
        type: 'itemNode',
        position: { x: 720, y: 450 },
        data: {
          name: 'Buffet Completo',
          subtitle: 'Serviço de Alimentos & Bebidas',
          description: 'Contratação completa do serviço de buffet artesanal com bolo, salgados e equipe de garçom para 100 convidados.',
          icon: 'Sparkles',
          quantity: 1,
          cost: 12000,
          unitType: 'currency',
          customUnit: '',
          tagId: 'bd-4',
          borderStyle: 'circle',
        },
      },
    ],
    edges: [
      {
        id: 'e-casa-casamento',
        source: 'comp-casa',
        target: 'goal-casamento',
        type: 'customEdge',
        animated: true,
        data: { label: '' },
      },
      {
        id: 'e-festa-casamento',
        source: 'comp-festa',
        target: 'goal-casamento',
        type: 'customEdge',
        animated: true,
        data: { label: '' },
      },
      {
        id: 'e-geladeira-casa',
        source: 'item-geladeira',
        target: 'comp-casa',
        type: 'customEdge',
        animated: true,
        data: { label: '1 un' },
      },
      {
        id: 'e-fogao-casa',
        source: 'item-fogao',
        target: 'comp-casa',
        type: 'customEdge',
        animated: true,
        data: { label: '1 un' },
      },
      {
        id: 'e-aluguel-casa',
        source: 'item-aluguel',
        target: 'comp-casa',
        type: 'customEdge',
        animated: true,
        data: { label: 'Fixo' },
      },
      {
        id: 'e-buffet-festa',
        source: 'item-buffet',
        target: 'comp-festa',
        type: 'customEdge',
        animated: true,
        data: { label: '100 convidados' },
      },
    ],
  },
  cake: {
    title: 'Receita: Bolo Simples',
    tags: [
      { id: 'cake-1', name: 'Seco', color: '#f59e0b' },
      { id: 'cake-2', name: 'Líquido', color: '#3b82f6' },
      { id: 'cake-3', name: 'Preparo', color: '#ff6a13' },
      { id: 'cake-4', name: 'Resultado', color: '#ec4899' },
    ],
    customUnits: ['xícara (chá)', 'colher (sopa)'],
    nodes: [
      {
        id: 'bolo-final',
        type: 'itemNode',
        position: { x: 480, y: 45 },
        data: {
          name: 'Bolo Simples',
          subtitle: 'Pronto para Servir',
          description: 'Deixe esfriar um pouco antes de desenformar. Finalize com açúcar de confeiteiro ou a calda de sua preferência.',
          icon: 'Cake',
          quantity: 1,
          cost: 0,
          unitType: 'none',
          customUnit: '',
          tagId: 'cake-4',
          borderStyle: 'diamond',
          collapsed: false,
        },
      },
      {
        id: 'station-forno',
        type: 'stationNode',
        position: { x: 480, y: 225 },
        data: {
          name: 'Assar em Forno • 40 min',
          subtitle: 'Forno Médio (180°C), Preaquecido',
          description: 'Transfira a massa para uma forma redonda com furo central (20cm), untada e enfarinhada, e asse até dourar e ficar seca por dentro.',
          icon: 'Flame',
          borderStyle: 'hexagon',
          tagId: 'cake-3',
          collapsed: false,
        },
      },
      {
        id: 'station-farinha',
        type: 'stationNode',
        position: { x: 480, y: 405 },
        data: {
          name: 'Incorporar Farinha e Fermento',
          subtitle: 'Massa Aerada',
          description: 'Incorpore a farinha aos poucos e delicadamente, e finalize com o fermento em pó, sem bater demais a massa.',
          icon: 'Layers',
          borderStyle: 'hexagon',
          tagId: 'cake-3',
          collapsed: false,
        },
      },
      {
        id: 'item-farinha',
        type: 'itemNode',
        position: { x: 230, y: 405 },
        data: {
          name: 'Farinha de Trigo',
          subtitle: 'Farinha de Trigo Comum',
          description: 'Acrescentada aos poucos e com cuidado para não perder a aeração conquistada na batida.',
          icon: 'Wheat',
          quantity: 2,
          cost: 0,
          unitType: 'custom',
          customUnit: 'xícara (chá)',
          tagId: 'cake-1',
          borderStyle: 'circle',
          collapsed: false,
        },
      },
      {
        id: 'item-fermento',
        type: 'itemNode',
        position: { x: 730, y: 405 },
        data: {
          name: 'Fermento em Pó',
          subtitle: 'Fermento Químico',
          description: 'Adicionado por último, é o responsável por fazer a massa crescer no forno.',
          icon: 'Wind',
          quantity: 1,
          cost: 0,
          unitType: 'custom',
          customUnit: 'colher (sopa)',
          tagId: 'cake-1',
          borderStyle: 'circle',
          collapsed: false,
        },
      },
      {
        id: 'station-liquidos',
        type: 'stationNode',
        position: { x: 480, y: 585 },
        data: {
          name: 'Adicionar Óleo e Leite',
          subtitle: 'Massa Homogênea',
          description: 'Misture bem o óleo e o leite ao creme de ovos e açúcar até formar uma massa lisa e uniforme.',
          icon: 'Combine',
          borderStyle: 'hexagon',
          tagId: 'cake-3',
          collapsed: false,
        },
      },
      {
        id: 'item-oleo',
        type: 'itemNode',
        position: { x: 230, y: 585 },
        data: {
          name: 'Óleo',
          subtitle: 'Óleo Vegetal',
          description: 'Confere umidade e maciez à massa, misturado junto ao leite.',
          icon: 'Droplet',
          quantity: 0.5,
          cost: 0,
          unitType: 'custom',
          customUnit: 'xícara (chá)',
          tagId: 'cake-2',
          borderStyle: 'circle',
          collapsed: false,
        },
      },
      {
        id: 'item-leite',
        type: 'itemNode',
        position: { x: 730, y: 585 },
        data: {
          name: 'Leite',
          subtitle: 'Leite Integral',
          description: 'Ajuda a homogeneizar a massa e deixa o miolo do bolo mais úmido.',
          icon: 'Milk',
          quantity: 1,
          cost: 0,
          unitType: 'custom',
          customUnit: 'xícara (chá)',
          tagId: 'cake-2',
          borderStyle: 'circle',
          collapsed: false,
        },
      },
      {
        id: 'station-creme',
        type: 'stationNode',
        position: { x: 480, y: 765 },
        data: {
          name: 'Bater Ovos e Açúcar',
          subtitle: 'Creme Claro e Fofo',
          description: 'Bata os ovos com o açúcar até formar um creme claro e aerado — a etapa que define a textura final do bolo.',
          icon: 'Blend',
          borderStyle: 'hexagon',
          tagId: 'cake-3',
          collapsed: false,
        },
      },
      {
        id: 'item-ovos',
        type: 'itemNode',
        position: { x: 330, y: 765 },
        data: {
          name: 'Ovos',
          subtitle: 'Base Proteica e Aeração',
          description: 'Batidos com o açúcar até formar um creme claro e fofo — a etapa que dá liga e leveza à massa.',
          icon: 'Egg',
          quantity: 3,
          cost: 0,
          unitType: 'custom',
          customUnit: '',
          tagId: 'cake-2',
          borderStyle: 'circle',
          collapsed: false,
        },
      },
      {
        id: 'item-acucar',
        type: 'itemNode',
        position: { x: 630, y: 765 },
        data: {
          name: 'Açúcar',
          subtitle: 'Açúcar Refinado',
          description: 'Batido junto com os ovos até dobrar de volume e clarear — a base da fofura do bolo.',
          icon: 'Candy',
          quantity: 1,
          cost: 0,
          unitType: 'custom',
          customUnit: 'xícara (chá)',
          tagId: 'cake-1',
          borderStyle: 'circle',
          collapsed: false,
        },
      },
    ],
    edges: [
      {
        id: 'e-ovos-creme',
        source: 'item-ovos',
        target: 'station-creme',
        type: 'customEdge',
        animated: true,
        data: { label: '3 ovos' },
      },
      {
        id: 'e-acucar-creme',
        source: 'item-acucar',
        target: 'station-creme',
        type: 'customEdge',
        animated: true,
        data: { label: '1 xícara' },
      },
      {
        id: 'e-creme-liquidos',
        source: 'station-creme',
        target: 'station-liquidos',
        type: 'customEdge',
        animated: true,
        data: { label: 'creme fofo' },
      },
      {
        id: 'e-oleo-liquidos',
        source: 'item-oleo',
        target: 'station-liquidos',
        type: 'customEdge',
        animated: true,
        data: { label: '1/2 xícara' },
      },
      {
        id: 'e-leite-liquidos',
        source: 'item-leite',
        target: 'station-liquidos',
        type: 'customEdge',
        animated: true,
        data: { label: '1 xícara' },
      },
      {
        id: 'e-liquidos-farinha',
        source: 'station-liquidos',
        target: 'station-farinha',
        type: 'customEdge',
        animated: true,
        data: { label: 'massa homogênea' },
      },
      {
        id: 'e-farinha-farinha',
        source: 'item-farinha',
        target: 'station-farinha',
        type: 'customEdge',
        animated: true,
        data: { label: '2 xícaras' },
      },
      {
        id: 'e-fermento-farinha',
        source: 'item-fermento',
        target: 'station-farinha',
        type: 'customEdge',
        animated: true,
        data: { label: '1 colher' },
      },
      {
        id: 'e-farinha-forno',
        source: 'station-farinha',
        target: 'station-forno',
        type: 'customEdge',
        animated: true,
        data: { label: 'massa aerada' },
      },
      {
        id: 'e-forno-bolo',
        source: 'station-forno',
        target: 'bolo-final',
        type: 'customEdge',
        animated: true,
        data: { label: '40 min • 180°C' },
      },
    ],
  },
};

const TEMPLATES_EN: Record<string, TemplateData> = {
  blank: {
    title: 'My Vulcanode Project',
    tags: [
      { id: 't-1', name: 'Common', color: '#64748b' },
      { id: 't-2', name: 'Rare', color: '#f59e0b' },
      { id: 't-3', name: 'Legendary', color: '#ff6a13' },
      { id: 't-4', name: 'Furniture', color: '#ea580c' },
      { id: 't-5', name: 'Component', color: '#10b981' },
    ],
    customUnits: ['pcs', 'kg', 'un', 'bars'],
    nodes: [],
    edges: [],
  },
  rpg: {
    title: 'Crafting Tree: Vulcan Masterblade',
    tags: [
      { id: 'rpg-1', name: 'Common', color: '#71717a' },
      { id: 'rpg-2', name: 'Uncommon', color: '#10b981' },
      { id: 'rpg-3', name: 'Rare', color: '#3b82f6' },
      { id: 'rpg-4', name: 'Legendary', color: '#a855f7' },
      { id: 'rpg-5', name: 'Mythic', color: '#ff6a13' },
    ],
    customUnits: ['bars', 'gems', 'un'],
    nodes: [
      {
        id: 'item-espada',
        type: 'itemNode',
        position: { x: 480, y: 45 },
        data: {
          name: 'Vulcan Masterblade',
          subtitle: 'Mythic Weapon of the Solar Forge',
          description: 'A blade capable of cutting through mountains, forged in the centuries-old flames of Mount Etna by the God of Fire himself.',
          url: 'https://en.wikipedia.org/wiki/Vulcan_(mythology)',
          icon: 'Sword',
          quantity: 1,
          cost: 1500,
          unitType: 'currency',
          customUnit: '',
          tagId: 'rpg-5',
          borderStyle: 'diamond',
          collapsed: false,
        },
      },
      {
        id: 'station-forja',
        type: 'stationNode',
        position: { x: 480, y: 255 },
        data: {
          name: 'Solar Furnace • 5 min',
          subtitle: 'Mandatory Smelting Station',
          description: 'A mandatory time passage through incandescent magma heat to bind ores and flames together.',
          icon: 'Flame',
          borderStyle: 'hexagon',
          collapsed: false,
        },
      },
      {
        id: 'item-ferro',
        type: 'itemNode',
        position: { x: 300, y: 435 },
        data: {
          name: 'Refined Iron Ore',
          subtitle: 'Standard Metal Component',
          description: 'Heavy blocks of metal extracted from the volcanic heart of the rock.',
          icon: 'Box',
          quantity: 5,
          cost: 20,
          unitType: 'custom',
          customUnit: 'bars',
          tagId: 'rpg-1',
          borderStyle: 'circle',
          collapsed: false,
        },
      },
      {
        id: 'item-carvao',
        type: 'itemNode',
        position: { x: 660, y: 435 },
        data: {
          name: 'Magma Coal',
          subtitle: 'ETERNAL Fire Fuel',
          description: 'Flames encapsulated in dark minerals that release constant explosive energy.',
          icon: 'Zap',
          quantity: 3,
          cost: 50,
          unitType: 'custom',
          customUnit: 'gems',
          tagId: 'rpg-2',
          borderStyle: 'circle',
          collapsed: false,
        },
      },
    ],
    edges: [
      {
        id: 'e-forja-espada',
        source: 'station-forja',
        target: 'item-espada',
        type: 'customEdge',
        animated: true,
        data: { label: 'Perfect Smelting' },
      },
      {
        id: 'e-ferro-forja',
        source: 'item-ferro',
        target: 'station-forja',
        type: 'customEdge',
        animated: true,
        data: { label: '5 bars' },
      },
      {
        id: 'e-carvao-forja',
        source: 'item-carvao',
        target: 'station-forja',
        type: 'customEdge',
        animated: true,
        data: { label: '3 gems' },
      },
    ],
  },
  budget: {
    title: 'Modular Composition: Wedding & Home',
    tags: [
      { id: 'bd-1', name: 'Furniture', color: '#ff6a13' },
      { id: 'bd-2', name: 'Appliances', color: '#ea580c' },
      { id: 'bd-3', name: 'Fixed Component', color: '#f59e0b' },
      { id: 'bd-4', name: 'Main Goal', color: '#ff6a13' },
    ],
    customUnits: ['pcs', 'm²', 'month', 'un'],
    nodes: [
      // Final Goal: Wedding at the top (Parent)
      {
        id: 'goal-casamento',
        type: 'itemNode',
        position: { x: 510, y: 45 },
        data: {
          name: 'Wedding & Home',
          subtitle: 'A Shared Life Project',
          description: 'The top of our modular composition tree, joining the costs of housing and the celebration party.',
          icon: 'Heart',
          quantity: 1,
          cost: 0,
          unitType: 'currency',
          customUnit: '',
          tagId: 'bd-4',
          borderStyle: 'diamond',
          collapsed: false,
        },
      },
      // Intermediate parents in the middle layer
      {
        id: 'comp-casa',
        type: 'itemNode',
        position: { x: 300, y: 240 },
        data: {
          name: 'Home Composition',
          subtitle: 'Furniture & Rent of the New Home',
          description: 'Sum of all essential structural and appliance components.',
          icon: 'Home',
          quantity: 1,
          cost: 0,
          unitType: 'currency',
          customUnit: '',
          tagId: 'bd-3',
          borderStyle: 'rounded',
          collapsed: false,
        },
      },
      {
        id: 'comp-festa',
        type: 'itemNode',
        position: { x: 720, y: 240 },
        data: {
          name: 'Celebration & Party',
          subtitle: 'Event and Catering',
          description: 'A special reception with catering and celebration with friends.',
          icon: 'Sparkles',
          quantity: 1,
          cost: 0,
          unitType: 'currency',
          customUnit: '',
          tagId: 'bd-4',
          borderStyle: 'rounded',
          collapsed: false,
        },
      },
      // Base components (ingredients/supplies) below
      {
        id: 'item-geladeira',
        type: 'itemNode',
        position: { x: 135, y: 450 },
        data: {
          name: 'Stainless Fridge',
          subtitle: 'Essential Appliance',
          description: '450-liter Frost Free refrigerator with inverter technology and A+++ energy savings.',
          icon: 'Box',
          quantity: 1,
          cost: 3000,
          unitType: 'currency',
          customUnit: '',
          tagId: 'bd-2',
          borderStyle: 'circle',
        },
      },
      {
        id: 'item-fogao',
        type: 'itemNode',
        position: { x: 300, y: 450 },
        data: {
          name: 'Cooktop Stove',
          subtitle: '5-Burner Oven & Stove',
          description: 'Tempered glass cooktop with fast flames for home cooking.',
          icon: 'Flame',
          quantity: 1,
          cost: 2000,
          unitType: 'currency',
          customUnit: '',
          tagId: 'bd-2',
          borderStyle: 'circle',
        },
      },
      {
        id: 'item-aluguel',
        type: 'itemNode',
        position: { x: 465, y: 450 },
        data: {
          name: "Month's Rent",
          subtitle: 'Recurring Housing Expense',
          description: 'Monthly expense with apartment rent and condo fees.',
          icon: 'Key',
          quantity: 1,
          cost: 1500,
          unitType: 'currency',
          customUnit: '',
          tagId: 'bd-3',
          borderStyle: 'circle',
        },
      },
      {
        id: 'item-buffet',
        type: 'itemNode',
        position: { x: 720, y: 450 },
        data: {
          name: 'Full Catering Service',
          subtitle: 'Food & Beverage Service',
          description: 'Full artisanal catering service with cake, appetizers and waitstaff for 100 guests.',
          icon: 'Sparkles',
          quantity: 1,
          cost: 12000,
          unitType: 'currency',
          customUnit: '',
          tagId: 'bd-4',
          borderStyle: 'circle',
        },
      },
    ],
    edges: [
      {
        id: 'e-casa-casamento',
        source: 'comp-casa',
        target: 'goal-casamento',
        type: 'customEdge',
        animated: true,
        data: { label: '' },
      },
      {
        id: 'e-festa-casamento',
        source: 'comp-festa',
        target: 'goal-casamento',
        type: 'customEdge',
        animated: true,
        data: { label: '' },
      },
      {
        id: 'e-geladeira-casa',
        source: 'item-geladeira',
        target: 'comp-casa',
        type: 'customEdge',
        animated: true,
        data: { label: '1 un' },
      },
      {
        id: 'e-fogao-casa',
        source: 'item-fogao',
        target: 'comp-casa',
        type: 'customEdge',
        animated: true,
        data: { label: '1 un' },
      },
      {
        id: 'e-aluguel-casa',
        source: 'item-aluguel',
        target: 'comp-casa',
        type: 'customEdge',
        animated: true,
        data: { label: 'Fixed' },
      },
      {
        id: 'e-buffet-festa',
        source: 'item-buffet',
        target: 'comp-festa',
        type: 'customEdge',
        animated: true,
        data: { label: '100 guests' },
      },
    ],
  },
  cake: {
    title: 'Recipe: Simple Cake',
    tags: [
      { id: 'cake-1', name: 'Dry', color: '#f59e0b' },
      { id: 'cake-2', name: 'Liquid', color: '#3b82f6' },
      { id: 'cake-3', name: 'Prep Step', color: '#ff6a13' },
      { id: 'cake-4', name: 'Result', color: '#ec4899' },
    ],
    customUnits: ['cup', 'tablespoon'],
    nodes: [
      {
        id: 'bolo-final',
        type: 'itemNode',
        position: { x: 480, y: 45 },
        data: {
          name: 'Simple Cake',
          subtitle: 'Ready to Serve',
          description: 'Let it cool slightly before unmolding. Finish with powdered sugar or your favorite glaze.',
          icon: 'Cake',
          quantity: 1,
          cost: 0,
          unitType: 'none',
          customUnit: '',
          tagId: 'cake-4',
          borderStyle: 'diamond',
          collapsed: false,
        },
      },
      {
        id: 'station-forno',
        type: 'stationNode',
        position: { x: 480, y: 225 },
        data: {
          name: 'Bake in the Oven • 40 min',
          subtitle: 'Preheated Medium Oven (350°F)',
          description: 'Pour the batter into a greased and floured 8-inch round tube pan, and bake until golden and dry inside.',
          icon: 'Flame',
          borderStyle: 'hexagon',
          tagId: 'cake-3',
          collapsed: false,
        },
      },
      {
        id: 'station-farinha',
        type: 'stationNode',
        position: { x: 480, y: 405 },
        data: {
          name: 'Fold in Flour and Baking Powder',
          subtitle: 'Aerated Batter',
          description: 'Gently fold in the flour a little at a time, and finish with the baking powder, without overmixing the batter.',
          icon: 'Layers',
          borderStyle: 'hexagon',
          tagId: 'cake-3',
          collapsed: false,
        },
      },
      {
        id: 'item-farinha',
        type: 'itemNode',
        position: { x: 230, y: 405 },
        data: {
          name: 'Wheat Flour',
          subtitle: 'All-Purpose Flour',
          description: 'Added little by little and gently, to avoid losing the aeration built up while beating.',
          icon: 'Wheat',
          quantity: 2,
          cost: 0,
          unitType: 'custom',
          customUnit: 'cup',
          tagId: 'cake-1',
          borderStyle: 'circle',
          collapsed: false,
        },
      },
      {
        id: 'item-fermento',
        type: 'itemNode',
        position: { x: 730, y: 405 },
        data: {
          name: 'Baking Powder',
          subtitle: 'Chemical Leavening',
          description: "Added last, it's what makes the batter rise in the oven.",
          icon: 'Wind',
          quantity: 1,
          cost: 0,
          unitType: 'custom',
          customUnit: 'tablespoon',
          tagId: 'cake-1',
          borderStyle: 'circle',
          collapsed: false,
        },
      },
      {
        id: 'station-liquidos',
        type: 'stationNode',
        position: { x: 480, y: 585 },
        data: {
          name: 'Add Oil and Milk',
          subtitle: 'Smooth Batter',
          description: 'Thoroughly mix the oil and milk into the egg-and-sugar cream until you get a smooth, even batter.',
          icon: 'Combine',
          borderStyle: 'hexagon',
          tagId: 'cake-3',
          collapsed: false,
        },
      },
      {
        id: 'item-oleo',
        type: 'itemNode',
        position: { x: 230, y: 585 },
        data: {
          name: 'Oil',
          subtitle: 'Vegetable Oil',
          description: 'Adds moisture and softness to the batter, mixed in together with the milk.',
          icon: 'Droplet',
          quantity: 0.5,
          cost: 0,
          unitType: 'custom',
          customUnit: 'cup',
          tagId: 'cake-2',
          borderStyle: 'circle',
          collapsed: false,
        },
      },
      {
        id: 'item-leite',
        type: 'itemNode',
        position: { x: 730, y: 585 },
        data: {
          name: 'Milk',
          subtitle: 'Whole Milk',
          description: "Helps smooth out the batter and keeps the cake's crumb moist.",
          icon: 'Milk',
          quantity: 1,
          cost: 0,
          unitType: 'custom',
          customUnit: 'cup',
          tagId: 'cake-2',
          borderStyle: 'circle',
          collapsed: false,
        },
      },
      {
        id: 'station-creme',
        type: 'stationNode',
        position: { x: 480, y: 765 },
        data: {
          name: 'Beat Eggs and Sugar',
          subtitle: 'Light, Fluffy Cream',
          description: "Beat the eggs with the sugar until you get a pale, airy cream — the step that shapes the cake's final texture.",
          icon: 'Blend',
          borderStyle: 'hexagon',
          tagId: 'cake-3',
          collapsed: false,
        },
      },
      {
        id: 'item-ovos',
        type: 'itemNode',
        position: { x: 330, y: 765 },
        data: {
          name: 'Eggs',
          subtitle: 'Protein Base & Aeration',
          description: "Beaten with the sugar until light and fluffy — the step that gives the batter its lift and structure.",
          icon: 'Egg',
          quantity: 3,
          cost: 0,
          unitType: 'custom',
          customUnit: '',
          tagId: 'cake-2',
          borderStyle: 'circle',
          collapsed: false,
        },
      },
      {
        id: 'item-acucar',
        type: 'itemNode',
        position: { x: 630, y: 765 },
        data: {
          name: 'Sugar',
          subtitle: 'Refined Sugar',
          description: "Creamed together with the eggs until doubled in volume and pale — the foundation of the cake's fluffiness.",
          icon: 'Candy',
          quantity: 1,
          cost: 0,
          unitType: 'custom',
          customUnit: 'cup',
          tagId: 'cake-1',
          borderStyle: 'circle',
          collapsed: false,
        },
      },
    ],
    edges: [
      {
        id: 'e-ovos-creme',
        source: 'item-ovos',
        target: 'station-creme',
        type: 'customEdge',
        animated: true,
        data: { label: '3 eggs' },
      },
      {
        id: 'e-acucar-creme',
        source: 'item-acucar',
        target: 'station-creme',
        type: 'customEdge',
        animated: true,
        data: { label: '1 cup' },
      },
      {
        id: 'e-creme-liquidos',
        source: 'station-creme',
        target: 'station-liquidos',
        type: 'customEdge',
        animated: true,
        data: { label: 'fluffy cream' },
      },
      {
        id: 'e-oleo-liquidos',
        source: 'item-oleo',
        target: 'station-liquidos',
        type: 'customEdge',
        animated: true,
        data: { label: '1/2 cup' },
      },
      {
        id: 'e-leite-liquidos',
        source: 'item-leite',
        target: 'station-liquidos',
        type: 'customEdge',
        animated: true,
        data: { label: '1 cup' },
      },
      {
        id: 'e-liquidos-farinha',
        source: 'station-liquidos',
        target: 'station-farinha',
        type: 'customEdge',
        animated: true,
        data: { label: 'smooth batter' },
      },
      {
        id: 'e-farinha-farinha',
        source: 'item-farinha',
        target: 'station-farinha',
        type: 'customEdge',
        animated: true,
        data: { label: '2 cups' },
      },
      {
        id: 'e-fermento-farinha',
        source: 'item-fermento',
        target: 'station-farinha',
        type: 'customEdge',
        animated: true,
        data: { label: '1 tbsp' },
      },
      {
        id: 'e-farinha-forno',
        source: 'station-farinha',
        target: 'station-forno',
        type: 'customEdge',
        animated: true,
        data: { label: 'aerated batter' },
      },
      {
        id: 'e-forno-bolo',
        source: 'station-forno',
        target: 'bolo-final',
        type: 'customEdge',
        animated: true,
        data: { label: '40 min • 350°F' },
      },
    ],
  },
};

/** Registro dos templates de exemplo por idioma. O conteúdo (nomes, descrições, tags) muda; posições, ícones e custos são iguais. */
export const TEMPLATES_BY_LANGUAGE: Record<TemplateLanguage, Record<string, TemplateData>> = {
  pt: TEMPLATES_PT,
  en: TEMPLATES_EN,
};
